version: '3'
services:
  db:
    image: ankane/pgvector
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: askmydocs
    ports:
      - "5432:5432"
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/askmydocs
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - db
