name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run build
      - run: npm test || true
      - uses: docker/setup-buildx-action@v3
      - run: docker build -t ghcr.io/${{ github.repository }}:latest .
      - run: echo "badge placeholder"
